[target.aarch64-unknown-linux-gnu]
# Use a custom image with GTK and GUI dependencies pre-installed
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"

# Pre-build command to install required packages
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y libgtk-3-dev:arm64 libglib2.0-dev:arm64 libcairo2-dev:arm64 libpango1.0-dev:arm64 libgdk-pixbuf2.0-dev:arm64 libatk1.0-dev:arm64"
]
